### ISSUE TITLE
Plants disappear

### ISSUE THREAD

**Issue by TRiXXER76** [qbcore-framework/qb-weed#12]
Hey, Im trying to find the issue by myself but couldnt do it... Maybe you can help.

Issue:

Im in my House and place Plants. They Spawn and they are working. But after a few minutes (I still was nearby the Plants) the first 3 Plants disappeared. Then after the next few minutes another few Plants disappeared. Also the Label and so on is there. I can interact with the Plant. The Plants are all updating in the Server Prompt but they are "Invisible" or "despawned" I think. I dont know why its happening.

Thanks in Advance

Greetings TRiXER

**Comment by GhzGarage** [comment]
Could not replicate the issue please ask for support in the discord. discord.gg/qbcore
