### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by EvilGnome93** [qbcore-framework/qb-weed#16]
Hi.

I went through al script and finally understand it haha. But I'm unable to find a place to buy the seeds?

Also how can I make the growing part go faster?

Thanks in advance!

**Comment by CptNoHand** [comment]
I wish I knew the place where to buy them too

**Comment by EvilGnome93** [comment]
I know everything already, thanks to the awsome qbus community. @CptNoHand  slide in my dm 😬

Discord: gnome#5136
