### ISSUE TITLE
can you tell me the location of the weed farm and processing.

### ISSUE THREAD

**Issue by ProGhoster21** [qbcore-framework/qb-weed#20]
can you tell me the location of the weed farm and processing.
it would be really helpful if you could send the cords thanks.

**Comment by DougJudy69** [comment]
u get weed seeds and u plant them in ur house and wait 6 rl hours for them to grow.

**Comment by slnlrp** [comment]
You need to add weed_white-widow_seed, weed_skunk_seed, weed_purple-haze_seed, weed_og-kush_seed, weed_amnesia_seed, weed_ak47_seed items to somewhere shop (Ours they can buy from Superfly shop). Then in your house, you need to use that seeds from the inventory. Then it will place the plant (keep remember to have a necessary gap between the plants). You need to take care of them. If nutrition for the plants is low you need to add fertilizers to plants. After some time (Ours 6 hours) you can harvest them and buy empty plastic bags and use Inventory to combine weed and plastic bags to create weed bags. That's it

**Comment by XxTeamslayer8xX** [comment]
@slnlrp How do you change the Time of Harvest? No mater if I switch the 40*1000 to 1*1 or 1000*1000 it doesn't change the time it takes to harvest

**Comment by vixmxstudio** [comment]
Because when I want to plant it tells me that it "is not safe here try in your house" I am supposed to be inside my house.?
