### ISSUE TITLE
I cant plant seed 

### ISSUE THREAD

**Issue by vixmxstudio** [qbcore-framework/qb-weed#29]
Because when I want to plant it tells me that it is not safe here try in your house I am supposed to be inside my house.

**Comment by XxTeamslayer8xX** [comment]
Yes you have to grow in a house you own. It cannot be outside or in a trap house.

**Comment by vixmxstudio** [comment]
I already tried it in a house that I own but it does not work, it tells me that it is not a house that I own. It will be some house bought from the real state
