### ISSUE TITLE
Cant find how to buy the seed>>

### ISSUE THREAD

**Issue by PhenixBtW** [qbcore-framework/qb-weed#3]
So basically installed this script onto my server but i cant seem to find the place where i can get the weed seeds can someone pls help Thanks...

**Comment by bakedbeangaming** [comment]
> 

did you sort this im stuck same

**Comment by CarlBishop** [comment]
Read the code or search youtube

**Comment by bakedbeangaming** [comment]
sorted thank you

**Comment by dcrogers28** [comment]
I have read the scripts and either I don't know what I'm looking for or I am missing it.  can not find where to get the seeds.  any help.  it is v1.0.0.
