### ISSUE TITLE
Edit Harvest Time / Growing pattern.

### ISSUE THREAD

**Issue by XxTeamslayer8xX** [qbcore-framework/qb-weed#30]

**Comment by XxTeamslayer8xX** [comment]
How to change the harvest time? Or what is the pattern you have to follow to make them grow? I see in the harvest time it says 40*1000 but regardless how I change it, there is no affect on the harvest time.

**Comment by Kxcp3r** [comment]
> How to change the harvest time? Or what is the pattern you have to follow to make them grow? I see in the harvest time it says 40*1000 but regardless how I change it, there is no affect on the harvest time.

How do u change it?
