### ISSUE TITLE
QB weed growing time. 

### ISSUE THREAD

**Issue by madness2891** [qbcore-framework/qb-weed#35]
Can anyone tell me how to change the grow time for inside a house as at the min it has been over 24 hours and still not done. Everywhere i have look i cant found it. I really dont want people to use it in my city unless i can turn down the growing time

**Comment by mrkamilmr** [comment]
> Can anyone tell me how to change the grow time for inside a house as at the min it has been over 24 hours and still not done. Everywhere i have look i cant found it. I really dont want people to use it in my city unless i can turn down the growing time

I need help with this issue asap as well. I went into config.lua and tried messing around with the harvest time. I've been messing with it for over two days and I honestly can't tell if I see a difference that I want. Try 1 * 1 for me real quick as well. I am testing decimals right now (they seem a little bit faster).

**Comment by mrkamilmr** [comment]
I could be tripping though, maybe there is no difference...

**Comment by FjamZoo** [comment]
You can change this in the server side: https://github.com/qbcore-framework/qb-weed/blob/main/server/main.lua
