### ISSUE TITLE
[Request]Looking for a way to make qb-target works in this script

### ISSUE THREAD

**Issue by Christina1734** [qbcore-framework/qb-weed#37]
one of my player asking for this.
sadly I haven't find any solution yet.
does anyone got intel of this?

**Comment by restray** [comment]
Good morning? Please?
What are you talking about? What have you tried to do?
(I think the Dev Team will close your ticket waiting courtesy from you.)

**Comment by FjamZoo** [comment]
No response since april, and this is a feature we are already wanting to implement into this script just stay put.
