### ISSUE TITLE
Plants not showing grow cycle correctly

### ISSUE THREAD

**Issue by DisguisedOG** [qbcore-framework/qb-weed#38]
Not sure what is causing this but, I had it working fine up  until about 5 days ago where I rebuilt my server with the latest qbcore files from the ground up due to a database error I had created.

Fresh files and database I test qb-weed and it grows fine but sometimes the plants when refreshing will turn into bkr_prop_weed_01_small_01b stacked on top of each other instead of a singular bkr_prop_weed_med_01b. (no errors in console)

I'm baffled as a beginner noting that the script is untouched. as shown with the only strain I'm using below.

QBWeed.Plants = {
    ["og-kush"] = {
        ["label"] = "OGKush",
        ["item"] = "weed_og-kush",
        ["stages"] = {
            ["stage-a"] = "bkr_prop_weed_01_small_01c",
            ["stage-b"] = "bkr_prop_weed_01_small_01b",
            ["stage-c"] = "bkr_prop_weed_01_small_01a",
            ["stage-d"] = "bkr_prop_weed_med_01b",
            ["stage-e"] = "bkr_prop_weed_lrg_01a",
            ["stage-f"] = "bkr_prop_weed_lrg_01b",
            ["stage-g"] = "bkr_prop_weed_lrg_01b",
        },
        
  Whilst using stock interiors included in the framework. This could be interior related as I sometimes can't exit my house with qb-target unless I relog.

**Comment by modways** [comment]
> Not sure what is causing this but, I had it working fine up until about 5 days ago where I rebuilt my server with the latest qbcore files from the ground up due to a database error I had created.
> 
> Fresh files and database I test qb-weed and it grows fine but sometimes the plants when refreshing will turn into bkr_prop_weed_01_small_01b stacked on top of each other instead of a singular bkr_prop_weed_med_01b. (no errors in console)
> 
> I'm baffled as a beginner noting that the script is untouched. as shown with the only strain I'm using below.
> 
> QBWeed.Plants = { ["og-kush"] = { ["label"] = "OGKush", ["item"] = "weed_og-kush", ["stages"] = { ["stage-a"] = "bkr_prop_weed_01_small_01c", ["stage-b"] = "bkr_prop_weed_01_small_01b", ["stage-c"] = "bkr_prop_weed_01_small_01a", ["stage-d"] = "bkr_prop_weed_med_01b", ["stage-e"] = "bkr_prop_weed_lrg_01a", ["stage-f"] = "bkr_prop_weed_lrg_01b", ["stage-g"] = "bkr_prop_weed_lrg_01b", },
> 
> Whilst using stock interiors included in the framework. This could be interior related as I sometimes can't exit my house with qb-target unless I relog.

Did u find the solution? Cos it wont grow for some reasons.

**Comment by jeann2013** [comment]
I was yesterday august 31th all day testing and the growth does it perfectly, with the latest version of qb-core and the latest version of this resource
