### ISSUE TITLE
Rolling up harvested weed

### ISSUE THREAD

**Issue by Dizzy92** [qbcore-framework/qb-weed#39]
As the title says, our server downloaded realistic smoking but the problem is how can we roll up to actually smoke our product we have made even in this script I'm not sure how to roll up any help is appreciated! Thank you!

**Comment by Shotgunner187** [comment]
If I understand correctly, You have to put the weed and the rolling papers in your 1-6 slot. Put a 1 in the how much to use slot and then drag the weed over the rolling papers and then it will say combine right under use/give. Click combine. Must have a lighter also.

**Comment by FjamZoo** [comment]
as explained above thats how you do it.
