### ISSUE TITLE
[BUG] Plant prop update flying

### ISSUE THREAD

**Issue by milotiro95** [qbcore-framework/qb-weed#46]
**Describe the bug**
If we are more than 1 into the place where you are growing your weed here the conflict you have. A lot of flying weeds wonderfull for beautiful RP moment. Serious RP Assumed.
![screenshot](https://user-images.githubusercontent.com/86166328/171970220-91709033-7aa5-4714-8011-792b4b7e2e39.jpg)
![screenshot2](https://user-images.githubusercontent.com/86166328/171970221-0955a90d-2a91-4d13-a907-a04c48bcf8d2.jpg)

**Comment by GhzGarage** [comment]
They planted them in the same spot?

**Comment by milotiro95** [comment]
Nop it is just when multiple players is into the place and planting together but not at the same position. When the server restart all is back ok but every time I plant we have this bug :/ don't understand why

**Comment by MafiaBorn** [comment]
I have same issue

**Comment by amgmacht** [comment]
i also have the same problem

**Comment by jeann2013** [comment]
I already tested with a version of this resource more than 1 month ago and the same thing happened to me, in fact it was working fine but it may be an issue more of fivem than of the resource itself, I'm testing to solve it.

**Comment by jeann2013** [comment]
couldn’t reproduce this issue

**Comment by OfficialRDB** [comment]
I think it happened after the stage check. (I am active in the building)
![Capture](https://user-images.githubusercontent.com/50579206/192727340-fd6d2f43-618b-4470-89de-73b57fccec7c.PNG)
![Capture](https://user-images.githubusercontent.com/50579206/192729895-58df36b0-53e2-45bc-a031-4857abf8904f.PNG)

**Comment by jeann2013** [comment]
@OfficialRDB  But after check stage put the plants right position, this happen when put feed

**Comment by Fear6682** [comment]
I'm getting the same issue, but sometimes it duplicates them in the air and sometimes it just places them in the ceiling

**Comment by jeann2013** [comment]
@Fear6682 for this reason we should limit the quantity of plants, what you think?

**Comment by midz8** [comment]
Did this get ressolved?

**Comment by jeann2013** [comment]
Yes, because limit quantity plants
