### ISSUE TITLE
times[BUG]

### ISSUE THREAD

**Issue by YPYE1** [qbcore-framework/qb-weed#48]
no way limit the amount of plants you can grow or change the times on how long it takes the plants to grow the times in config do not effect anything

**Comment by WicketsArcade** [comment]
You can limit the stages to reduce grow time. For instance, 2 stages instead of 5. But yes an acutal GrowTime variable would be a nice enhancement.

**Comment by jeann2013** [comment]
@YPYE1 You can try change the growing time and stages in the config.lua file of the resource, 

from **line 2 QBWeed.HarvestTime = 40 * 1000** to **QBWeed.HarvestTime = 40 * 100**

you can change this:

**["stages"] = {
            ["stage-a"] = "bkr_prop_weed_01_small_01c",
            ["stage-b"] = "bkr_prop_weed_01_small_01b",
            ["stage-c"] = "bkr_prop_weed_01_small_01a",
            ["stage-d"] = "bkr_prop_weed_med_01b",
            ["stage-e"] = "bkr_prop_weed_lrg_01a",
            ["stage-f"] = "bkr_prop_weed_lrg_01b",
            ["stage-g"] = "bkr_prop_weed_lrg_01b",
}**

to

**["stages"] = {
            ["stage-a"] = "bkr_prop_weed_01_small_01c",
            ["stage-g"] = "bkr_prop_weed_lrg_01b"
}**

**Comment by OfficialRDB** [comment]
> 

At a collomn to the house_plants table called citizenid
Make sure you save the citizenid to the database when they are planting.
You can do that in qb-weed > server.lua under the event qb-weed:server:placePlant

Then add a check how many they already have in the database.
```
RegisterNetEvent('qb-weed:server:placePlant', function(coords, sort, currentHouse)
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    local result = MySQL.prepare.await('SELECT COUNT(*) FROM house_plants WHERE citizenid = ?', {Player.PlayerData.citizenid})

    if result < QBWeed.MaxPlants then
        MySQL.insert('INSERT INTO house_plants (citizenid, building, coords, sort, plantid) VALUES (?, ?, ?, ?, ?)',
        {Player.PlayerData.citizenid, currentHouse, coords, sort, math.random(111111, 999999)})
        TriggerClientEvent('qb-weed:client:refreshHousePlants', -1, currentHouse)
    else
        TriggerClientEvent('QBCore:Notify', src, Lang:t('error.max_plants'), 'error')
    end
end)
```

Add to the config.
`QBWeed.MaxPlants = 10`

That's it. Works fine for me.

**Comment by jeann2013** [comment]
@OfficialRDB Thanks I will this implementation, thanks
