### ISSUE TITLE
Weed plants do not remove after being harvested

### ISSUE THREAD

**Issue by DannysRP** [qbcore-framework/qb-weed#5]
People in my server can harvest the same plant over and over again. When it refreshes the plant does not get remove from the database. Players also cannot remove dead plants, assuming it's because they don't remove from the database off refresh. I have a fresh installed version as well, no F8 or console errors. This started when the SQL changes were made to the script

**Comment by BerkieBb** [comment]
Fixed with https://github.com/qbcore-framework/qb-weed/commit/298f3f63dcf1caf85077acd8eb67ebca8775a777
