### ISSUE TITLE
I know everything already, thanks to the awsome qbus community. @CptNoHand  slide in my dm 😬

### ISSUE THREAD

**Issue by itzzjd123** [qbcore-framework/qb-weed#58]
I know everything already, thanks to the awsome qbus community. @CptNoHand  slide in my dm 😬

Discord: gnome#5136

_Originally posted by @EvilGnome93 in https://github.com/qbcore-framework/qb-weed/issues/16#issuecomment-922432411_
            Hey bro could you please help me out as well with this. I am having the worst of troubles too. My discord is ItzzJD. Please help.

**Comment by Mat40** [comment]
hi can you describe your problem
